"""Use enums for role and plan_tier

Revision ID: 792c45386ef9
Revises: c1997413f93b
Create Date: 2026-07-16 13:52:00.045934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792c45386ef9'
down_revision: Union[str, Sequence[str], None] = 'c1997413f93b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    userrole = sa.Enum('student', 'instructor', 'admin', name='userrole')
    userrole.create(op.get_bind(), checkfirst=True)
    plantier = sa.Enum('free', 'basic', 'premium', name='plantier')
    plantier.create(op.get_bind(), checkfirst=True)

    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=userrole,
               existing_nullable=False,
               postgresql_using="role::userrole")
    op.alter_column('users', 'plan_tier',
               existing_type=sa.VARCHAR(),
               type_=plantier,
               existing_nullable=False,
               postgresql_using="plan_tier::plantier")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'plan_tier',
               existing_type=sa.Enum('free', 'basic', 'premium', name='plantier'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('student', 'instructor', 'admin', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    
    plantier = sa.Enum('free', 'basic', 'premium', name='plantier')
    plantier.drop(op.get_bind(), checkfirst=True)
    userrole = sa.Enum('student', 'instructor', 'admin', name='userrole')
    userrole.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
